name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout Mochimo
        uses: actions/checkout@v3
        with:
          repository: mochimodev/mochimo
      - name: version
        run: echo "::set-output name=version::$(git describe --always --tags --abrev=0)"
        id: version
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }} - Mochimo ${{ steps.version.outputs.version }}
  matrix-cuda:
    strategy:
      matrix:
        cuda: [11.4.4, 11.5.2, 11.6.2, 11.7.1, 11.8.0]
        include:
          - cuda: 11.4.4
            nvidia: 470.82.01
          - cuda: 11.5.2
            nvidia: 495.29.05
          - cuda: 11.6.2
            nvidia: 510.47.03
          - cuda: 11.7.1
            nvidia: 515.65.01
          - cuda: 11.8.0
            nvidia: 520.61.05
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Set up build
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential
          wget -q https://developer.download.nvidia.com/compute/cuda/${{ matrix.cuda }}/local_installers/cuda_${{ matrix.cuda }}_${{ matrix.nvidia }}_linux.run
          sudo sh cuda_${{ matrix.cuda }}_${{ matrix.nvidia }}_linux.run --override --toolkit --silent --no-drm
      - name: Checkout Mochimo
        uses: actions/checkout@v3
        with:
          repository: mochimodev/mochimo
      - name: Build package
        run: |
          git submodule update --init --recursive
          make cleanall install-cudaminer NVCFLAGS=-arch=sm_61
          mv bin/miner bin/mcmminer-pascal
          make cleanall install-cudaminer
          mv bin/miner bin/mcmminer
          cd bin
          cp /usr/local/cuda/lib64/libcudart.so.11.0 .
          cp /usr/local/cuda/lib64/stubs/libnvidia-ml.so .
          tar zcvf mcmminer-${{ needs.release.outputs.version }}.ubuntu.cuda-${{ matrix.cuda }}-${{ matrix.nvidia }}.tar.gz *
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: bin/mcmminer-${{ needs.release.outputs.version }}.ubuntu.cuda-${{ matrix.cuda }}-${{ matrix.nvidia }}.tar.gz
          tag: ${{ github.ref }}
